apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"users-api","namespace":"microservice-app"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"users-api"}},"template":{"metadata":{"labels":{"app":"users-api"}},"spec":{"containers":[{"env":[{"name":"JAVA_TOOL_OPTIONS","value":"--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED\n"}],"image":"chechoiot/users-api:latest","name":"users-api","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"50m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-10-25T15:26:35Z"
  generation: 14
  name: users-api
  namespace: microservice-app
  resourceVersion: "8437"
  uid: 5aae1032-ce35-4201-aabf-e3778be1a007
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: users-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-25T11:00:52-05:00"
      labels:
        app: users-api
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: |
            --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
        image: chechoiot/users-api:latest
        imagePullPolicy: Always
        name: users-api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-25T16:00:31Z"
    lastUpdateTime: "2025-10-25T16:00:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-25T16:57:26Z"
    lastUpdateTime: "2025-10-25T17:00:19Z"
    message: ReplicaSet "users-api-7f8c6b49d7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 14
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
