apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: microservice-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
        version: v1
    spec:
      containers:
        - name: todos-api
          image: chechoiot/todos-api:latest
          ports:
            - containerPort: 8082
          env:
            - name: REDIS_HOST
              value: "redis.microservice-app.svc.cluster.local"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
