apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: chechoiot/users-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservice-app
spec:
  selector:
    app: users-api
  ports:
    - port: 8080
      targetPort: 8080

